### PR TITLE
Custom content filter

### PR DESCRIPTION
**Pull request by madc**
This PR adds an option to execute custom filter functions before init and after deinit.

```
    ...
    custom_filter: ['functionname_1', functionname2'],
    ...
```

```
    ...
    custom_filter: [function(canvas, isInit) { /* code */ }, 'functionname2'],
    ...
```

### CODE REVIEW

**Comment by Epskampie** [comment]
Thanks for making the PR. Three points:
- I don't see any reason for this option to accept an **array** of functions, as it is trivially easy to call multiple functions yourself, i.e.

```
custom_filter: function() {
  functionname_1();
  functionname_2();
}
```

Sorry for being picky, but I really want to keep the API as easy and simple as is possible without impeding flexibility. :-) 
- Please add an example to the option in the README. This makes it much more clear and easy for beginners. The examples you posted in this thread are excellent, please make the README entry just as excellent. :-)
- Small thing, but please configure your editor as to not change whitespace (delete trailing spaces). This makes it a lot harder to review your pull requests.

That's it!

**Comment by madc** [comment]
Please excuse my response time. I'll take a closer look and update the PR.

**Comment by madc** [comment]
Did you have tome to have a look yet?

**Comment by Epskampie** [comment]
Please excuse the long wait, i hadn't seen you updated the PR.
I've made a new release that includes this function.

Thanks for your work!

**Comment by madc** [comment]
Great stuff, thanks!

**Pull request merged**
